---
title: "educ-multilevel-models"
author: "Peter Silverstein"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tinytex")
```


```{r}
library(tidyverse)
library(rstanarm)
library(knitr)
library(kableExtra)
library(magick)
library(webshot2)
library(broom.mixed)
```



```{r}
merged_data <- read_csv("data/processed data/merged/merged_df.csv")
merged_data <- merged_data %>%
  mutate(governor = as.numeric(governor),
         senate = as.numeric(senate),
         house = as.numeric(house),
         unified_control = ifelse(abs(governor + senate + house) == 3, 1, 0),
         r_unified_control = ifelse(governor + senate + house == 3, 1, 0),
         d_unified_control = ifelse(governor + senate + house == -3, 1, 0)
  )
```

# Unified Party Control of State Government Per Year
```{r}
percbyyear <- merged_data %>%
  group_by(Year) %>%
  summarize(Republican = mean(r_unified_control, na.rm = TRUE),
            Democrat = mean(d_unified_control, na.rm = TRUE)) %>%
  pivot_longer(cols = c("Democrat","Republican"),
               names_to = "Party",
               values_to = "Percentage")

control_byyear_plot <- ggplot(data = percbyyear, aes(x = Year, 
                                                      y = Percentage,
                                                      color = Party)) + 
  geom_line(lwd = 2) + 
  scale_color_manual(values = c("Democrat" = "blue", "Republican" = "red")) + 
  #theme_minimal() + 
  labs(title = "Figure 1: Proportion of Unified Party Control of State Government Per Year") + 
  scale_x_continuous(
    breaks = c(1997, 2001, 2005, 2009, 2013), 
    labels = c("1997", "2001", "2005", "2009", "2013")
  )

control_byyear_plot
```

```{r}

ggsave("figures/Figure_1.png", 
       plot = control_byyear_plot, 
       width = 8, height = 6)

```


## Summary Statistics

### Dimension
```{r}
dim(merged_data)
```


```{r}
mean_educ_spending_by_year <- merged_data %>%
  filter(State != "NE") %>%          
  group_by(Year) %>%
  summarize(mean_educ_spending = mean(educ_spending, na.rm = TRUE)) %>%
  ungroup()

mean_educ_spending_by_year
```



```{r}

#ggsave("figures/Figure_2.png", 
#       plot = Figure_2, 
#       width = 8, height = 6)

```


### Mean Education Spending by State 

```{r}

mean_educ_spending_by_state <- merged_data %>%
  group_by(State) %>%
  summarize(
    mean_educ_spending = mean(educ_spending, na.rm = TRUE),
    mean_r_unified_control = mean(r_unified_control, na.rm = TRUE)
  ) %>%
  filter(!is.na(mean_educ_spending), !is.na(mean_r_unified_control)) %>%
  mutate(State = reorder(State, -mean_educ_spending)) %>%  
  ungroup()

mean_educ_spending_by_state

```



```{r}

Figure_2 <- ggplot(mean_educ_spending_by_state, aes(x = mean_r_unified_control, y = mean_educ_spending, label = State)) +
  geom_text(color = "black", size = 3) +
  labs(
    title = "Figure 2: Mean Education Spending Per Pupil vs Republican Unified Control by State",
    x = "Mean Republican Unified Control",
    y = "Mean Education Spending (2016 USD)"
  )

Figure_2

```

```{r}

ggsave("figures/Figure_2.png", 
       plot = Figure_2, 
       width = 8, height = 6)

```



# Modeling

```{r}
set.seed(42)

# Model 1: Linear Regression of Education Spending on Unified Control
fit1 <- stan_glm(log(educ_spending) ~ unified_control,
                   data = merged_data,
                   refresh = FALSE,
                   cores = 4)

print(fit1, digits = 3)
```



```{r}
set.seed(42)

# Model 2: Multilevel Regression of Education Spending + Covariates on Unified 
# Control w/ varying slopes for Time and State
fit2 <- stan_glmer(log(educ_spending) ~ unified_control +
                     under19_pop_prct + 
                     white_pop_prct + 
                     income_adj + 
                     unemployment_rate + 
                     (1 | State) + 
                     (1 | Year),
                   data = merged_data,
                   refresh = FALSE,
                   cores = 4)

print(fit2, digits = 3)
```

```{r}
set.seed(42)

# Model 3: Multilevel Regression of Education Spending + Covariates on Unified 
# Party Control w/ varying slopes for Time and State
fit3 <- stan_glmer(log(educ_spending) ~ r_unified_control + 
                     d_unified_control + 
                     under19_pop_prct + 
                     white_pop_prct + 
                     income_adj + 
                     unemployment_rate + 
                     (1 | State) + 
                     (1 | Year),
                   data = merged_data,
                   refresh = FALSE,
                   cores = 4)

print(fit3, digits = 3)
```

```{r}

fit1_tidy <- tidy(fit1)
fit1_tidy_rounded <- fit1_tidy  %>%
  mutate(across(where(is.numeric),
                ~ifelse(is.na(.), "-", format(round(., 3), nsmall = 3)))) %>%
  mutate(across(where(~!is.numeric(.)),
                ~ifelse(is.na(.), "-", as.character(.))))
fit1_kable <- knitr::kable(fit1_tidy_rounded, caption = "Model 1 Results") %>% kable_classic()
save_kable(fit1_kable, file = "fit1table.png")

fit2_tidy <- tidy(fit2)
fit2_tidy_rounded <- fit2_tidy %>%
  mutate(across(where(is.numeric),
                ~ifelse(is.na(.), "-", format(round(., 3), nsmall = 3)))) %>%
  mutate(across(where(~!is.numeric(.)),
                ~ifelse(is.na(.), "-", as.character(.))))
fit2_kable <- knitr::kable(fit2_tidy_rounded, caption = "Model 2 Results") %>% kable_classic()
save_kable(fit2_kable, file = "fit2table.png")

fit3_tidy <- tidy(fit3)
fit3_tidy_rounded <- fit3_tidy %>%
  mutate(across(where(is.numeric),
                ~ifelse(is.na(.), "-", format(round(., 3), nsmall = 3)))) %>%
  mutate(across(where(~!is.numeric(.)),
                ~ifelse(is.na(.), "-", as.character(.))))
fit3_kable <- knitr::kable(fit3_tidy_rounded, caption = "Model 3 Results") %>% kable_classic()
save_kable(fit3_kable, file = "fit3table.png")

```






