---
title: "income-preprocessing"
author: "Sam Gartenstein"
date: "2025-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyr)
library(dplyr)

```


```{r}
path <- "data/raw-data/income"
```


```{r}
income_data <- read_csv(file.path(path, "Median Income.csv"))
head(income_data)

```

### Dropping Row where State is US
```{r}
income_data <- income_data %>%
  filter(State != "United States")

income_data
```



```{r}
# Create a named vector: names are full state names, values are abbreviations
state_abbreviations <- setNames(state.abb, state.name)

# Add abbreviation for "District of Columbia" 
state_abbreviations["District of Columbia"] <- "DC"

income_data <- income_data %>%
  mutate(State = state_abbreviations[State])

income_data
```

### Averaging 2013

Since there are two values for 2013, I will take the average 

```{r}
income_data <- income_data %>%
  mutate(`2013` = (`2013 (39)` + `2013 (38)`) / 2)

income_data
```

```{r}
income_data <- income_data %>%
  select(-`2013 (39)`, -`2013 (38)`)

income_data
```

https://tidyselect.r-lib.org/reference/everything.html

```{r}
income_data <- income_data %>%
  select(State, `2013`, `2012`, everything())

income_data
```

### Pivotting Data to Long

https://tidyr.tidyverse.org/reference/pivot_longer.html

```{r}

# Pivot all year columns into long format
income_long <- income_data %>%
  pivot_longer(
    cols = -State,                      
    names_to = "Year",                 
    values_to = "Income"                
  ) %>%
  mutate(
    Year = as.integer(Year)            
  )

income_long

```


```{r}
income_long <- income_long %>%
  arrange(State, Year)

income_long
```


```{r}
income_df <- income_long
income_df
```

### Adjusting for Inflation 2016

https://www.usinflationcalculator.com/

2013: 1.03

2012: 1.05

2011: 1.07

2010: 1.10

2009: 1.12

2008: 1.11

2007: 1.16

2006: 1.19

2005: 1.23

2004: 1.27

2003: 1.30

2002: 1.33

2001: 1.36

2000: 1.39

1999: 1.44

1998: 1.47

1997: 1.50

```{r}
adjustment_factors <- c(
  `2013` = 1.03,
  `2012` = 1.05,
  `2011` = 1.07,
  `2010` = 1.10,
  `2009` = 1.12,
  `2008` = 1.11,
  `2007` = 1.16,
  `2006` = 1.19,
  `2005` = 1.23,
  `2004` = 1.27,
  `2003` = 1.30,
  `2002` = 1.33,
  `2001` = 1.36,
  `2000` = 1.39,
  `1999` = 1.44,
  `1998` = 1.47,
  `1997` = 1.50
)

income_df <- income_df %>%
  mutate(income_adj = Income * adjustment_factors[as.character(Year)])

income_df
```



```{r}
write.csv(income_df, "data/processed data/individual/income_df.csv", row.names = FALSE)

```



